// @generated by protoc-gen-es v1.2.1 with parameter "target=ts"
// @generated from file nibiru/sudo/v1/event.proto (package nibiru.sudo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf"
import { Message, proto3 } from "@bufbuild/protobuf"
import { Sudoers } from "./state_pb.js"

/**
 * @generated from message nibiru.sudo.v1.EventUpdateSudoers
 */
export class EventUpdateSudoers extends Message<EventUpdateSudoers> {
  /**
   * @generated from field: nibiru.sudo.v1.Sudoers sudoers = 1;
   */
  sudoers?: Sudoers

  /**
   * Action is the type of update that occured to the "sudoers"
   *
   * @generated from field: string action = 2;
   */
  action = ""

  constructor(data?: PartialMessage<EventUpdateSudoers>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = "nibiru.sudo.v1.EventUpdateSudoers"
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sudoers", kind: "message", T: Sudoers },
    { no: 2, name: "action", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventUpdateSudoers {
    return new EventUpdateSudoers().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventUpdateSudoers {
    return new EventUpdateSudoers().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventUpdateSudoers {
    return new EventUpdateSudoers().fromJsonString(jsonString, options)
  }

  static equals(
    a: EventUpdateSudoers | PlainMessage<EventUpdateSudoers> | undefined,
    b: EventUpdateSudoers | PlainMessage<EventUpdateSudoers> | undefined,
  ): boolean {
    return proto3.util.equals(EventUpdateSudoers, a, b)
  }
}
