// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/sudo/v1/query.proto (package nibiru.sudo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QuerySudoersRequest, QuerySudoersResponse } from "./query_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service nibiru.sudo.v1.Query
 */
export const Query = {
  typeName: "nibiru.sudo.v1.Query",
  methods: {
    /**
     * @generated from rpc nibiru.sudo.v1.Query.QuerySudoers
     */
    querySudoers: {
      name: "QuerySudoers",
      I: QuerySudoersRequest,
      O: QuerySudoersResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
