// @generated by protoc-gen-es v1.2.1 with parameter "target=ts"
// @generated from file nibiru/sudo/v1/query.proto (package nibiru.sudo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf"
import { Message, proto3 } from "@bufbuild/protobuf"
import { Sudoers } from "./state_pb.js"

/**
 * @generated from message nibiru.sudo.v1.QuerySudoersRequest
 */
export class QuerySudoersRequest extends Message<QuerySudoersRequest> {
  constructor(data?: PartialMessage<QuerySudoersRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = "nibiru.sudo.v1.QuerySudoersRequest"
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): QuerySudoersRequest {
    return new QuerySudoersRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): QuerySudoersRequest {
    return new QuerySudoersRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): QuerySudoersRequest {
    return new QuerySudoersRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: QuerySudoersRequest | PlainMessage<QuerySudoersRequest> | undefined,
    b: QuerySudoersRequest | PlainMessage<QuerySudoersRequest> | undefined,
  ): boolean {
    return proto3.util.equals(QuerySudoersRequest, a, b)
  }
}

/**
 * QuerySudoersResponse indicates the successful execution of MsgEditSudeors.
 *
 * @generated from message nibiru.sudo.v1.QuerySudoersResponse
 */
export class QuerySudoersResponse extends Message<QuerySudoersResponse> {
  /**
   * @generated from field: nibiru.sudo.v1.Sudoers sudoers = 1;
   */
  sudoers?: Sudoers

  constructor(data?: PartialMessage<QuerySudoersResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = "nibiru.sudo.v1.QuerySudoersResponse"
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sudoers", kind: "message", T: Sudoers },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): QuerySudoersResponse {
    return new QuerySudoersResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): QuerySudoersResponse {
    return new QuerySudoersResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): QuerySudoersResponse {
    return new QuerySudoersResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: QuerySudoersResponse | PlainMessage<QuerySudoersResponse> | undefined,
    b: QuerySudoersResponse | PlainMessage<QuerySudoersResponse> | undefined,
  ): boolean {
    return proto3.util.equals(QuerySudoersResponse, a, b)
  }
}
