// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/sudo/v1/tx.proto (package nibiru.sudo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgEditSudoers, MsgEditSudoersResponse } from "./tx_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Msg defines the x/sudo module's Msg service. Protobuf `Msg` services are
 * called from `BaseApp` instances during `DeliverTx`. The `Msg` service will be
 * responsible for processing `sdk.Msg` requests.
 *
 * @generated from service nibiru.sudo.v1.Msg
 */
export const Msg = {
  typeName: "nibiru.sudo.v1.Msg",
  methods: {
    /**
     * EditSudoers updates the "Sudoers" state
     *
     * @generated from rpc nibiru.sudo.v1.Msg.EditSudoers
     */
    editSudoers: {
      name: "EditSudoers",
      I: MsgEditSudoers,
      O: MsgEditSudoersResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
