// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/epochs/v1/query.proto (package nibiru.epochs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  QueryCurrentEpochRequest,
  QueryCurrentEpochResponse,
  QueryEpochsInfoRequest,
  QueryEpochsInfoResponse,
} from "./query_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service nibiru.epochs.v1.Query
 */
export const Query = {
  typeName: "nibiru.epochs.v1.Query",
  methods: {
    /**
     * EpochInfos provide running epochInfos
     *
     * @generated from rpc nibiru.epochs.v1.Query.EpochInfos
     */
    epochInfos: {
      name: "EpochInfos",
      I: QueryEpochsInfoRequest,
      O: QueryEpochsInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CurrentEpoch provide current epoch of specified identifier
     *
     * @generated from rpc nibiru.epochs.v1.Query.CurrentEpoch
     */
    currentEpoch: {
      name: "CurrentEpoch",
      I: QueryCurrentEpochRequest,
      O: QueryCurrentEpochResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
