// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/inflation/v1/query.proto (package nibiru.inflation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  QueryCirculatingSupplyRequest,
  QueryCirculatingSupplyResponse,
  QueryEpochMintProvisionRequest,
  QueryEpochMintProvisionResponse,
  QueryInflationRateRequest,
  QueryInflationRateResponse,
  QueryParamsRequest,
  QueryParamsResponse,
  QueryPeriodRequest,
  QueryPeriodResponse,
  QuerySkippedEpochsRequest,
  QuerySkippedEpochsResponse,
} from "./query_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Query provides defines the gRPC querier service.
 *
 * @generated from service nibiru.inflation.v1.Query
 */
export const Query = {
  typeName: "nibiru.inflation.v1.Query",
  methods: {
    /**
     * Period retrieves current period.
     *
     * @generated from rpc nibiru.inflation.v1.Query.Period
     */
    period: {
      name: "Period",
      I: QueryPeriodRequest,
      O: QueryPeriodResponse,
      kind: MethodKind.Unary,
    },
    /**
     * EpochMintProvision retrieves current minting epoch provision value.
     *
     * @generated from rpc nibiru.inflation.v1.Query.EpochMintProvision
     */
    epochMintProvision: {
      name: "EpochMintProvision",
      I: QueryEpochMintProvisionRequest,
      O: QueryEpochMintProvisionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SkippedEpochs retrieves the total number of skipped epochs.
     *
     * @generated from rpc nibiru.inflation.v1.Query.SkippedEpochs
     */
    skippedEpochs: {
      name: "SkippedEpochs",
      I: QuerySkippedEpochsRequest,
      O: QuerySkippedEpochsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CirculatingSupply retrieves the total number of tokens that are in
     * circulation (i.e. excluding unvested tokens).
     *
     * @generated from rpc nibiru.inflation.v1.Query.CirculatingSupply
     */
    circulatingSupply: {
      name: "CirculatingSupply",
      I: QueryCirculatingSupplyRequest,
      O: QueryCirculatingSupplyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * InflationRate retrieves the inflation rate of the current period.
     *
     * @generated from rpc nibiru.inflation.v1.Query.InflationRate
     */
    inflationRate: {
      name: "InflationRate",
      I: QueryInflationRateRequest,
      O: QueryInflationRateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Params retrieves the total set of minting parameters.
     *
     * @generated from rpc nibiru.inflation.v1.Query.Params
     */
    params: {
      name: "Params",
      I: QueryParamsRequest,
      O: QueryParamsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
