// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/perp/v2/query.proto (package nibiru.perp.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  QueryMarketsRequest,
  QueryMarketsResponse,
  QueryModuleAccountsRequest,
  QueryModuleAccountsResponse,
  QueryPositionRequest,
  QueryPositionResponse,
  QueryPositionsRequest,
  QueryPositionsResponse,
} from "./query_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service nibiru.perp.v2.Query
 */
export const Query = {
  typeName: "nibiru.perp.v2.Query",
  methods: {
    /**
     * @generated from rpc nibiru.perp.v2.Query.QueryPosition
     */
    queryPosition: {
      name: "QueryPosition",
      I: QueryPositionRequest,
      O: QueryPositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Query.QueryPositions
     */
    queryPositions: {
      name: "QueryPositions",
      I: QueryPositionsRequest,
      O: QueryPositionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Queries the reserve assets in a given pool, identified by a token pair.
     *
     * @generated from rpc nibiru.perp.v2.Query.ModuleAccounts
     */
    moduleAccounts: {
      name: "ModuleAccounts",
      I: QueryModuleAccountsRequest,
      O: QueryModuleAccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Query.QueryMarkets
     */
    queryMarkets: {
      name: "QueryMarkets",
      I: QueryMarketsRequest,
      O: QueryMarketsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
