// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/perp/v2/tx.proto (package nibiru.perp.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  MsgAddMargin,
  MsgAddMarginResponse,
  MsgClosePosition,
  MsgClosePositionResponse,
  MsgDonateToEcosystemFund,
  MsgDonateToEcosystemFundResponse,
  MsgMultiLiquidate,
  MsgMultiLiquidateResponse,
  MsgOpenPosition,
  MsgOpenPositionResponse,
  MsgRemoveMargin,
  MsgRemoveMarginResponse,
} from "./tx_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Msg defines the x/perp Msg service.
 *
 * @generated from service nibiru.perp.v2.Msg
 */
export const Msg = {
  typeName: "nibiru.perp.v2.Msg",
  methods: {
    /**
     * @generated from rpc nibiru.perp.v2.Msg.RemoveMargin
     */
    removeMargin: {
      name: "RemoveMargin",
      I: MsgRemoveMargin,
      O: MsgRemoveMarginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Msg.AddMargin
     */
    addMargin: {
      name: "AddMargin",
      I: MsgAddMargin,
      O: MsgAddMarginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Msg.MultiLiquidate
     */
    multiLiquidate: {
      name: "MultiLiquidate",
      I: MsgMultiLiquidate,
      O: MsgMultiLiquidateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Msg.OpenPosition
     */
    openPosition: {
      name: "OpenPosition",
      I: MsgOpenPosition,
      O: MsgOpenPositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Msg.ClosePosition
     */
    closePosition: {
      name: "ClosePosition",
      I: MsgClosePosition,
      O: MsgClosePositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.perp.v2.Msg.DonateToEcosystemFund
     */
    donateToEcosystemFund: {
      name: "DonateToEcosystemFund",
      I: MsgDonateToEcosystemFund,
      O: MsgDonateToEcosystemFundResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
