// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/stablecoin/v1/query.proto (package nibiru.stablecoin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  QueryCirculatingSupplies,
  QueryCirculatingSuppliesResponse,
  QueryLiquidityRatioInfoRequest,
  QueryLiquidityRatioInfoResponse,
  QueryModuleAccountBalances,
  QueryModuleAccountBalancesResponse,
  QueryParamsRequest,
  QueryParamsResponse,
} from "./query_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service nibiru.stablecoin.v1.Query
 */
export const Query = {
  typeName: "nibiru.stablecoin.v1.Query",
  methods: {
    /**
     * Parameters queries the parameters of the x/stablecoin module.
     *
     * @generated from rpc nibiru.stablecoin.v1.Query.Params
     */
    params: {
      name: "Params",
      I: QueryParamsRequest,
      O: QueryParamsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ModuleAccountBalances queries the account balance of x/stablecoin.
     *
     * @generated from rpc nibiru.stablecoin.v1.Query.ModuleAccountBalances
     */
    moduleAccountBalances: {
      name: "ModuleAccountBalances",
      I: QueryModuleAccountBalances,
      O: QueryModuleAccountBalancesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.stablecoin.v1.Query.CirculatingSupplies
     */
    circulatingSupplies: {
      name: "CirculatingSupplies",
      I: QueryCirculatingSupplies,
      O: QueryCirculatingSuppliesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nibiru.stablecoin.v1.Query.LiquidityRatioInfo
     */
    liquidityRatioInfo: {
      name: "LiquidityRatioInfo",
      I: QueryLiquidityRatioInfoRequest,
      O: QueryLiquidityRatioInfoResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
