// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/spot/v1/tx.proto (package nibiru.spot.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  MsgCreatePool,
  MsgCreatePoolResponse,
  MsgExitPool,
  MsgExitPoolResponse,
  MsgJoinPool,
  MsgJoinPoolResponse,
  MsgSwapAssets,
  MsgSwapAssetsResponse,
} from "./tx_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Msg defines the Msg service.
 *
 * @generated from service nibiru.spot.v1.Msg
 */
export const Msg = {
  typeName: "nibiru.spot.v1.Msg",
  methods: {
    /**
     * Used to create a pool.
     *
     * @generated from rpc nibiru.spot.v1.Msg.CreatePool
     */
    createPool: {
      name: "CreatePool",
      I: MsgCreatePool,
      O: MsgCreatePoolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Join a pool as a liquidity provider.
     *
     * @generated from rpc nibiru.spot.v1.Msg.JoinPool
     */
    joinPool: {
      name: "JoinPool",
      I: MsgJoinPool,
      O: MsgJoinPoolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Exit a pool position by returning LP shares
     *
     * @generated from rpc nibiru.spot.v1.Msg.ExitPool
     */
    exitPool: {
      name: "ExitPool",
      I: MsgExitPool,
      O: MsgExitPoolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Swap assets in a pool
     *
     * @generated from rpc nibiru.spot.v1.Msg.SwapAssets
     */
    swapAssets: {
      name: "SwapAssets",
      I: MsgSwapAssets,
      O: MsgSwapAssetsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
