// @generated by protoc-gen-es v1.2.1 with parameter "target=ts"
// @generated from file nibiru/oracle/v1/state.proto (package nibiru.oracle.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf"
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf"

/**
 * a snapshot of the prices at a given point in time
 *
 * @generated from message nibiru.oracle.v1.PriceSnapshot
 */
export class PriceSnapshot extends Message<PriceSnapshot> {
  /**
   * @generated from field: string pair = 1;
   */
  pair = ""

  /**
   * @generated from field: string price = 2;
   */
  price = ""

  /**
   * milliseconds since unix epoch
   *
   * @generated from field: int64 timestamp_ms = 3;
   */
  timestampMs = protoInt64.zero

  constructor(data?: PartialMessage<PriceSnapshot>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = "nibiru.oracle.v1.PriceSnapshot"
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pair", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timestamp_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PriceSnapshot {
    return new PriceSnapshot().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PriceSnapshot {
    return new PriceSnapshot().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PriceSnapshot {
    return new PriceSnapshot().fromJsonString(jsonString, options)
  }

  static equals(
    a: PriceSnapshot | PlainMessage<PriceSnapshot> | undefined,
    b: PriceSnapshot | PlainMessage<PriceSnapshot> | undefined,
  ): boolean {
    return proto3.util.equals(PriceSnapshot, a, b)
  }
}
