// @generated by protoc-gen-connect-es v0.10.1 with parameter "target=ts"
// @generated from file nibiru/oracle/v1/tx.proto (package nibiru.oracle.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  MsgAggregateExchangeRatePrevote,
  MsgAggregateExchangeRatePrevoteResponse,
  MsgAggregateExchangeRateVote,
  MsgAggregateExchangeRateVoteResponse,
  MsgDelegateFeedConsent,
  MsgDelegateFeedConsentResponse,
} from "./tx_pb.js"
import { MethodKind } from "@bufbuild/protobuf"

/**
 * Msg defines the oracle Msg service.
 *
 * @generated from service nibiru.oracle.v1.Msg
 */
export const Msg = {
  typeName: "nibiru.oracle.v1.Msg",
  methods: {
    /**
     * AggregateExchangeRatePrevote defines a method for submitting
     * aggregate exchange rate prevote
     *
     * @generated from rpc nibiru.oracle.v1.Msg.AggregateExchangeRatePrevote
     */
    aggregateExchangeRatePrevote: {
      name: "AggregateExchangeRatePrevote",
      I: MsgAggregateExchangeRatePrevote,
      O: MsgAggregateExchangeRatePrevoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AggregateExchangeRateVote defines a method for submitting
     * aggregate exchange rate vote
     *
     * @generated from rpc nibiru.oracle.v1.Msg.AggregateExchangeRateVote
     */
    aggregateExchangeRateVote: {
      name: "AggregateExchangeRateVote",
      I: MsgAggregateExchangeRateVote,
      O: MsgAggregateExchangeRateVoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DelegateFeedConsent defines a method for delegating oracle voting rights
     * to another address known as a price feeder.
     * See https://github.com/NibiruChain/pricefeeder.
     *
     * @generated from rpc nibiru.oracle.v1.Msg.DelegateFeedConsent
     */
    delegateFeedConsent: {
      name: "DelegateFeedConsent",
      I: MsgDelegateFeedConsent,
      O: MsgDelegateFeedConsentResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
